push every normal output to /dev/null.
therefore, write timings to stderr and afterwards switch stderr and
stdout, so that rebench can read stdout

diff --git a/bin/run-bigloo b/bin/run-bigloo
--- a/bin/run-bigloo
+++ b/bin/run-bigloo
@@ -29,7 +29,7 @@ OUT="bigloo/${BENCHMARK}${VARIABLE}.exe"
 BIGLOO_PRELUDE="${BIGLOO_PRELUDE:-configuration/definitions-bigloo.scm configuration/iterations.rkt}"
 BIGLOO_SPECIALIZE="configuration/specialize-bigloo$VARIABLE.scm"
 
-if [ ! -f "$SRC" ]; then echo "ERROR: no such benchmark"; exit 1; fi
+if [ ! -f "src/${BENCHMARK}.scm" ]; then echo "ERROR: no such benchmark"; exit 1; fi
 
 
 cat ${BIGLOO_PRELUDE} ${BIGLOO_SPECIALIZE} src/${BENCHMARK}.scm > ${SRC}
@@ -59,5 +59,5 @@ rm -f $OUT
 $BIGLOO "$@" $BIGLOO_UNSAFE $BIGLOO_ARITH $BIGLOO_CALLCC -eval '(set! *strip* #f)' -native -main "bigloo-main" -Obench \
   -copt "${BIGLOO_CFLAGS}" ${BIGLOO_LDFLAGS} \
   -o $OUT $SRC
-exec $OUT
+(exec $OUT 3>&2 2>&1 1>&3) 2>/dev/null
 
diff --git a/bin/run-gambit b/bin/run-gambit
--- a/bin/run-gambit
+++ b/bin/run-gambit
@@ -30,7 +30,7 @@ shift
 SRC="gambit/${BENCHMARK}${VARIABLE}.scm"
 OUT="gambit/${BENCHMARK}${VARIABLE}.exe"
 
-if [ ! -f "$SRC" ]; then echo "ERROR: no such benchmark"; exit 1; fi
+if [ ! -f "src/${BENCHMARK}.scm" ]; then echo "ERROR: no such benchmark"; exit 1; fi
 
 
 GAMBIT_PRELUDE="${GAMBIT_PRELUDE:-configuration/definitions-gambit.scm configuration/iterations.rkt}"
@@ -40,4 +40,4 @@ cat ${GAMBIT_PRELUDE} ${GAMBIT_SPECIALIZE} src/${BENCHMARK}.scm configuration/ma
 
 
 $GAMBIT "$@" -exe -cc-options "${GAMBIT_CC}" -ld-options "${GAMBIT_LD}" -o $OUT $SRC
-exec $OUT
+(exec $OUT 3>&2 2>&1 1>&3) 2>/dev/null
