Prepare chaperone benches (micro)

diff --git a/bin/run-larceny b/bin/run-larceny
--- a/bin/run-larceny
+++ b/bin/run-larceny
@@ -21,16 +21,31 @@ shift
 BENCHMARK=$1
 shift
 
-OUT="larceny/$BENCHMARK.fasl"
+if [ "$VARIABLE" = "CHAP" ]; then EXT=sch; else EXT=scm; fi
 
-$LARCENY -nobanner -- -e '(begin (herald #f) (repl-prompt values))' <<EOF
+SRC="src/$BENCHMARK.$EXT"
+OUT="larceny/$BENCHMARK.fasl"
+if [ ! -d larceny ]; then mkdir -p larceny; fi
+
+if [ ! -f "$SRC" ]; then echo "ERROR: no such benchmark"; exit 1; fi
+
+if [ "$VARIABLE" = "CHAP" ]; then
+  $LARCENY -r6rs <<EOF
+(import (rnrs) (larceny compiler))
+(compile-file "$SRC" "$OUT")
+EOF
+  exec $LARCENY -r6rs -program $OUT \
+       2>&1 | awk '/Error/ { sub("Error", "Warning") } /^Elapsed\ GC\ time/ { printf "RESULT-gc: %f\n", $4 } /^Elapsed\ time/ {printf "RESULT-cpu: %f\nRESULT-total: %f\n", $6, $3 } {print}'
+else
+
+  $LARCENY -nobanner -- -e '(begin (herald #f) (repl-prompt values))' <<EOF
 (begin
   (load "configuration/specialize-larceny$VARIABLE.scm")
-  (compile-file "src/$BENCHMARK.scm" "$OUT"))
+  (compile-file "$SRC" "$OUT"))
 EOF
 
-exec $LARCENY -nobanner -- -e '(begin (herald #f) (repl-prompt values))' <<EOF \
-    2>&1 | awk '/Error/ { sub("Error", "Warning") } /^Elapsed\ GC\ time/ { printf "RESULT-gc: %f\n", $4 } /^Elapsed\ time/ {printf "RESULT-cpu: %f\nRESULT-total: %f\n", $6, $3 } {print}'
+  exec $LARCENY -nobanner -- -e '(begin (herald #f) (repl-prompt values))' <<EOF \
+       2>&1 | awk '/Error/ { sub("Error", "Warning") } /^Elapsed\ GC\ time/ { printf "RESULT-gc: %f\n", $4 } /^Elapsed\ time/ {printf "RESULT-cpu: %f\nRESULT-total: %f\n", $6, $3 } {print}'
 (begin
   (load "configuration/definitions-larceny.scm")
   (load "configuration/iterations.rkt")
@@ -38,3 +53,4 @@ exec $LARCENY -nobanner -- -e '(begin (herald #f) (repl-prompt values))' <<EOF \
   (load "$OUT")
   (main))
 EOF
+fi
diff --git a/bin/run-pycket b/bin/run-pycket
--- a/bin/run-pycket
+++ b/bin/run-pycket
@@ -2,6 +2,7 @@
 PROGRAM=`echo $0 | sed 's%.*/%%'`
 PROGDIR="$(cd `dirname $0`; echo $PWD)"
 
+export LANG=C
 if [ ! -z "$ZSH_VERSION" ]; then
   setopt shwordsplit
 fi
@@ -23,7 +24,7 @@ shift
 BENCHMARK=$1
 shift
 
-if [ "$VARIABLE" = "PURE" ]; then
+if [ "$VARIABLE" = "PURE" -o "$VARIABLE" = "CHAP" ]; then
     OUT="src/${BENCHMARK}.rkt"
 else
     OUT="racket/${BENCHMARK}${VARIABLE}.rkt"
@@ -39,4 +40,12 @@ else
            > "$OUT";
 fi
 
-exec $PYCKET_BIN "$OUT" "$@"
+if [ ! -f "$OUT" ]; then echo "ERROR: no such benchmark"; exit 1; fi
+
+
+if [ "$VARIABLE" = "CHAP" ]; then
+    exec $PYCKET_BIN "$OUT" "$@" \
+    | awk '/^cpu time:/ {printf "RESULT-cpu: %f\nRESULT-gc: %f\nRESULT-total: %f\n", $3, $9, $6 } {print}'
+else
+    exec $PYCKET_BIN "$OUT" "$@"
+fi
diff --git a/bin/run-racket b/bin/run-racket
--- a/bin/run-racket
+++ b/bin/run-racket
@@ -2,6 +2,7 @@
 PROGRAM=`echo $0 | sed 's%.*/%%'`
 PROGDIR="$(cd `dirname $0`; echo $PWD)"
 
+export LANG=C
 if [ ! -z "$ZSH_VERSION" ]; then
   setopt shwordsplit
 fi
@@ -19,7 +20,7 @@ BENCHMARK=$1
 shift
 
 
-if [ "$VARIABLE" = "PURE" ]; then
+if [ "$VARIABLE" = "PURE" -o "$VARIABLE" = "CHAP" ]; then
     OUT="src/${BENCHMARK}.rkt"
 else
     OUT="racket/${BENCHMARK}${VARIABLE}.rkt"
@@ -35,6 +36,13 @@ else
            > "$OUT";
 fi
 
+if [ ! -f "$OUT" ]; then echo "ERROR: no such benchmark"; exit 1; fi
+
 raco make "$OUT"
 
-exec $RACKET ${RACKET_ARGS} "$OUT" "$@"
+if [ "$VARIABLE" = "CHAP" ]; then
+    exec $RACKET ${RACKET_ARGS} "$OUT" "$@" \
+    | awk '/^cpu time:/ {printf "RESULT-cpu: %f\nRESULT-gc: %f\nRESULT-total: %f\n", $3, $9, $6 } {print}'
+else
+    exec $RACKET ${RACKET_ARGS} "$OUT" "$@"
+fi
